image:
  file: .gitpod.Dockerfile

tasks:
  - init: composer install && php artisan key:generate
  - init: cp .env.example .env
  - init: npm install
    command: npm run dev
  - init: mysql -u root -e "create database cse"
    command: php artisan migrate --seed && php artisan serve
